# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('author', models.CharField(blank=True, db_index=True, max_length=200)),
                ('scripture', models.CharField(blank=True, db_index=True, max_length=100)),
                ('first_line', models.CharField(blank=True, db_index=True, max_length=300)),
                ('key_lyric', models.CharField(blank=True, db_index=True, max_length=300)),
                ('notes', models.CharField(blank=True, db_index=True, max_length=300)),
                ('quarantined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musictable.TagType'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, to='musictable.Tag'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musictable.Song'),
        ),
    ]
